-- Initialisation spécifiques pour un jeu de test
INSERT INTO Galerie(id, nom, adresse) VALUES (1, 'Saatchi', 'King\''s Road, Londres');
INSERT INTO Galerie(id, nom, adresse) VALUES (2, 'Louvre', 'Paris');
INSERT INTO Galerie(id, nom, adresse) VALUES (3, 'National Portrait Gallery', 'London');
INSERT INTO Galerie(id, nom, adresse) VALUES (4, 'Museu Salvador Dali', 'Figueras');
INSERT INTO Galerie(id, nom, adresse) VALUES (5,'Narodni muzeum','Praha');
INSERT INTO Artiste(id, nom, adresse, biographie) VALUES (1, 'Vincent Van Ghog', 'Pays-Bas', 'je me suis coupe une oreille');
INSERT INTO Artiste(id, nom, adresse, biographie) VALUES (2, 'Frida Kahlo', 'Mexico', 'tres attachee e mes racines mexicaines');
INSERT INTO Artiste(id, nom, adresse) VALUES (3,'Henri Matisse', 'France','Bonjour');
INSERT INTO Artiste(id, nom, adresse) VALUES (4, 'Andy Warhol', 'USA','Hello');
INSERT INTO Artiste(id, nom, adresse) VALUES (5, 'Alfred Sisley', 'France','Bonjour');
INSERT INTO Personne(id, nom, adresse) VALUES (6, 'Client1', 'Castres');
INSERT INTO Personne(id, nom, adresse) VALUES (7, 'Client2', 'Foix');
INSERT INTO Exposition (id, debut, intitule, duree, galerie) VALUES (1, TO_DATE('2021/01/28', 'YYYY/MM/DD'),'JR: Chronicles',20,1);
INSERT INTO Exposition (id, debut, intitule, duree, galerie) VALUES (2, TO_DATE('2022/02/07', 'YYYY/MM/DD'),'Pharaon des Deux Terres',30,2);
INSERT INTO Exposition (id, debut, intitule, duree, galerie) VALUES (3, TO_DATE('2020/08/31', 'YYYY/MM/DD'),'Slunecni kralove',52,5);
INSERT INTO Tableau (id, titre, support, largeur, hauteur, artiste) VALUES (1, 'Two Crabs', 'huile sur toile',38,47,1);
INSERT INTO Tableau (id, titre, support, largeur, hauteur, artiste) VALUES (2, 'Las Dos Fridas', 'huile sur toile',175,176,2);
INSERT INTO Transaction (id, venduLe, prixVente, exposition, personne, oeuvre) VALUES (1, TO_DATE('2021/01/15', 'YYYY/MM/DD'), 10 000, 1, 6, 1);
INSERT INTO Transaction (id, venduLe, prixVente, exposition, personne, oeuvre) VALUES (2, TO_DATE('2021/01/15', 'YYYY/MM/DD'), 10 000, 2, 7, 2);